version: :"3.8"
services:
  mongo:
    image: mongo:6.0
    ports:
      - "8001:27017"
    volumes:
      - mongo-data:/data/db
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
       - discovery.type=single-node
       - xpack.security.enabled=false
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "8002:9200"
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    ports:
      - "8003:5601"

volumes:
  mongo-data:

