version: "3.8"
services:
  indexer-worker:
    build:
      context: .
      dockerfile: DevOpsDemo.IndexerWorker/Dockerfile
    container_name: devops-demo-indexer-worker
    depends_on:
      elasticsearch:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      DOTNET_ENVIRONMENT: "Docker"
    restart: unless-stopped