apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsdemo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsdemo
  template:
    metadata:
      labels:
        app: devopsdemo
    spec:
      containers:
      - name: devopsdemo
        image: devopsdemoacr.azurecr.io/devops-demo:REPLACE_IMAGE_TAG
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /hello
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /hello
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: devopsdemo-service
  labels:
    app: devopsdemo
spec:
  type: LoadBalancer
  selector:
    app: devopsdemo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80