apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsdemo-deployment
  namespace: project-a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devopsdemo
  template:
    metadata:
      labels:
        app: devopsdemo
    spec:
      containers:
      - name: devopsdemo
        image: devopsdemoakshayacr.azurecr.io/devops-demo-api:cloud-test
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /hello
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /hello
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
            
        env:
          - name: MongoDbWebApi__ConnectionString
            valueFrom:
              secretKeyRef:
                name: project-a-secrets
                key: MongoDbWebApi__ConnectionString

          - name: MongoDbWebApi__DatabaseName
            value: productdb

          - name: MongoDbWebApi__CollectionName
            value: products

          - name: ElasticSearchWebApi__NodeUrl
            valueFrom:
              secretKeyRef:
                name: project-a-secrets
                key: ElasticSearchWebApi__NodeUrl

          - name: ElasticSearchWebApi__Username
            valueFrom:
              secretKeyRef:
                name: project-a-secrets
                key: ElasticSearchWebApi__Username

          - name: ElasticSearchWebApi__Password
            valueFrom:
              secretKeyRef:
                name: project-a-secrets
                key: ElasticSearchWebApi__Password
                
          - name: ElasticSearchWebApi__CloudId
            valueFrom:
              secretKeyRef:
                name: project-a-secrets
                key: ElasticSearchWebApi__CloudId

          - name: ElasticSearchWebApi__IndexName
            valueFrom:
              configMapKeyRef:
                name: project-a-config
                key: ElasticSearchWebApi__IndexName

          - name: ElasticSearchWebApi__IndexAlias
            valueFrom:
              configMapKeyRef:
                name: project-a-config
                key: ElasticSearchWebApi__IndexAlias

          - name: ElasticSearchWebApi__EnableChangeStreams
            valueFrom:
              configMapKeyRef:
                name: project-a-config
                key: ElasticSearchWebApi__EnableChangeStreams

      imagePullSecrets:
        - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: devopsdemo-service
  namespace: project-a
  labels:
    app: devopsdemo
spec:
  type: LoadBalancer
  selector:
    app: devopsdemo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80